// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Math Maven",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Math Maven",
            targets: ["AppModule"],
            bundleIdentifier: "-53982.SSC.MM",
            teamIdentifier: "G85D3VS6S4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",            
            resources: [
                .copy("Resources2")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)